### ISSUE TITLE
Field must not have a selection since type "String" has no subfields

### ISSUE THREAD

**Issue by xuopled** [escaladesports/gatsby-plugin-netlify-cms-paths#1]
Hi, I try to use your plugin because I have frontmatter like this:

```md
---
cover: /content/images/sunrise.jpg
---

I have this config:
```js
plugins: [
    "gatsby-plugin-netlify-cms-paths",
    {
      resolve: "gatsby-transformer-remark",
      options: {
        plugins: [
          "gatsby-plugin-netlify-cms-paths",
        ]
     }
  }
]
```

But I still have the following error when I build: 
```
Field "cover" must not have a selection since type "String" has no subfields.
```

Am I using your plugin the wrong way?

Thank you

**Comment by xuopled** [comment]
I'm not sure to understand what is the main difference for `media_folder` and `static__folder` for `netlify-cms`. The documentation is unclear about this. `public_folder` is not mandatory

**Comment by kennedyrose** [comment]
The media folder is where the images will be stored (relative to the root of the repo) once a user uploads them. The public folder is where they are available (relative to the root of the website) to view in the CMS widget. In the case of Gatsby the only way to make them publicly available without processing them is by putting them somewhere in the `static` folder.
