### ISSUE TITLE
Gatsby v2

### ISSUE THREAD

**Issue by TylerBarnes** [escaladesports/gatsby-plugin-netlify-cms-paths#2]
Will this plugin work with gatsby v2?

**Comment by kennedyrose** [comment]
We believe so. It's not quite as battle tested in v2, but we've been using it with v2 for a couple weeks and haven't seen any issues.

**Comment by TylerBarnes** [comment]
Awesome, I tried it out and it seems to work well. Thanks for the great plugin!

**Comment by TylerBarnes** [comment]
This isn't really related to this repo but is there a chance you could share a gatsby-config.js where you got this working? This plugin works but I'm having trouble getting gatsby-image to work with my netlifycms set up.

**Comment by kennedyrose** [comment]
The example in the readme should work. Make sure the image links in your markdown files are in the `./static` folder:

---yaml
img: /uploads/image-file.jpg
---
