### ISSUE TITLE
Convert paths recursively in nested objects

### ISSUE THREAD

**Issue by nakedible** [escaladesports/gatsby-plugin-netlify-cms-paths#3]
It is a common use case in Netlify CMS to have sub-objects or lists of sub-objects in Markdown frontmatter. This plugin should convert paths also in arrays, objects, arrays of objects, etc.

**Comment by mattbag** [comment]
+1 on that, very useful for the list and object widget!

**Comment by axelboc** [comment]
Works like a charm, thank you!
