### ISSUE TITLE
MDX support

### ISSUE THREAD

**Issue by mrozilla** [escaladesports/gatsby-plugin-netlify-cms-paths#9]
I ran into wanting to use this plugin for my MDX-based Gatsby pages and when quickly looking at the code it might be as simple as extending the node type check (focusing on frontmatter for now).

I'm happy to take a stab at a PR but wanted to check with your first for openness to such change and any issues you might already know about.

And cheers for your work so far!

**Comment by kennedyrose** [comment]
Sure as long as existing features all continue to work, we'd be fine with that.

**Comment by mrozilla** [comment]
I've actually found an existing solution in [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images#to-convert-frontmatter-images), so there doesn't seem to be the need to port it here, closing :)

**Comment by cloderic** [comment]
> I've actually found an existing solution in [gatsby-remark-relative-images](https://github.com/danielmahon/gatsby-remark-relative-images#to-convert-frontmatter-images), so there doesn't seem to be the need to port it here, closing :)

Well it's not an actual solution it means path needs to be changed, do you have your PR around ?

**Comment by cloderic** [comment]
Fixed in #12
